"""add Department

Revision ID: 6d5997c62b73
Revises: d60d2cedc2ec
Create Date: 2024-07-06 08:19:10.462386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5997c62b73'
down_revision = 'd60d2cedc2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employees', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'address')
    op.drop_table('department')
    # ### end Alembic commands ###
